apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts  # Public Helm repo
    chart: kube-prometheus-stack  # Helm chart name
    targetRevision: latest  # Use "latest" or specify a version like "51.2.0"
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/https://github.com/Ariel-ksenzovsky/GCP-terraform-argocd/main/charts/monitor/prom-values.yaml  # Adjust path to your values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
