apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "51.2.0"  # Check if valid
    helm:
      valueFiles:
        - prom-values.yaml  # File must exist in your repo
    sourceType: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
    createNamespace: true  # Ensure the namespace exists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
