apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: "27.5.1"  # Check if valid
    helm:
      valueFiles:
        - prom-values.yaml  # File must exist in your repo
    sourceType: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
    createNamespace: true  # Ensure the namespace exists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true  # Forces replacement instead of patching

