apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Grafana
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: Grafana
    targetRevision: "8.10.1"  # Check if valid
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
    createNamespace: true  # Ensure the namespace exists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true  # Forces replacement instead of patching

