apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki  
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "6.28.0"
    chart: loki
    helm:
      values: |
        loki:
          auth_enabled: false
          storage_config:
            boltdb_shipper:
              shared_store: null
          schema_config:
            configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: index_
                  period: 24h
          limits_config:
            retention_period: 24h
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
