apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: "27.5.1"
    helm:
      values: |
        server:
          persistentVolume:
            enabled: false  # Disable persistent volume for Prometheus server
          additionalScrapeConfigs: |
            - job_name: 'flask-app'
              kubernetes_sd_configs:
                - role: endpoints
                  namespaces:
                    names:
                      - default
              relabel_configs:
                - source_labels: [__meta_kubernetes_service_label_app]
                  action: keep
                  regex: flask-app  # Match the app label in your service
                - source_labels: [__meta_kubernetes_endpoint_port_name]
                  action: keep
                  regex: http  # Match the port name in your service
              metrics_path: /metrics
              scheme: http  # Use HTTP to scrape metrics
        serviceMonitor:
          enabled: false  # Disable serviceMonitor as we are directly configuring scrape jobs
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    manual: {}
