apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki  
  namespace: argocd  # Namespace where ArgoCD is running
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # ArgoCD project to which this app belongs
  source:
    repoURL: https://grafana.github.io/helm-charts  # Correct Grafana Helm repository
    targetRevision: "6.28.0"  # Correct version of Loki
    chart: loki  # Correct Helm chart for Loki 
  destination:
    server: https://kubernetes.default.svc 
    namespace: log  # Target namespace for the Loki app
  syncPolicy:
    automated: # Set to 'null' for manual sync
      selfHeal: true
      prune: true