apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana  # Lowercase name
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "8.10.1"  # Ensure this version is valid
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    manual: {}
