apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-servicemonitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ariel-ksenzovsky/GCP-terraform-argocd.git
    targetRevision: main
    path: charts/monitor
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
