apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.10.1
    chart: grafana
    helm:
      values: |
        datasource:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: loki
              type: loki-datasource
              url: http://loki.monitor.svc.cluster.local:3100
              access: proxy
              uid: loki
        service:
          type: LoadBalancer
        persistence:
          enabled: true
          size: 10Gi
        adminPassword: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true


