apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "6.17.4"
    helm:
      values: |
        adminPassword: admin
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
