apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  destination:
    namespace: monitor
    server: https://kubernetes.default.svc  
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts  # Using Grafana's Helm repo
    chart: loki-stack
    targetRevision: "2.10.1" # Can be a specific version, e.g., "2.11.0"
    helm:
      values: |
        loki:
          image:
            tag: "2.9.3"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
