name: CI-Helm

on:
  push:
    branches: [ "main" ]
    paths:
      - "charts/flask-app/**"
  
  pull_request:
    branches: [ "main" ]
    paths:
      - "charts/flask-app/**"

  workflow_run:
    workflows: ["CI-image"]  # This must match the name of the CI workflow
    types:
      - completed

concurrency:
  group: ci-helm-${{ github.ref_name }}  # Each branch has its own concurrency group
  cancel-in-progress: true  # Cancel previous runs on the same branch

jobs:
  setup-build-publish-deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}  # Ensure the job runs only if CI succeeds
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    steps:

      - name: sleep 60 seconds for concurrency
        run: |
          sleep 60

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials # for s3 tf remote state - accessing s3 bucket.
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Update Helm Chart Version
        run: |
          CHART_VERSION="1.0.${{ github.run_number }}"
          echo "Updating Chart version to $CHART_VERSION"
          sed -i "s/^version:.*/version: $CHART_VERSION/" charts/flask-app/Chart.yaml
          cat charts/flask-app/Chart.yaml  # Debugging to verify update

      - name: Download Image Tag Artifact from CI-image - Only If Triggered By CI-image
        if: ${{ github.event.workflow_run.name == 'CI-image' }}
        uses: actions/download-artifact@v4
        with:
          name: version
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.REPO_TOKEN }}
          

      - name: Update Image Tag in values.yaml - Only If Triggered By CI-image
        if: ${{ github.event.workflow_run.name == 'CI-image' }}
        run: |
          set -x
          ls -lrta
          VERSION=$(cat version.txt)
          echo "updating image tag in values.yaml to ${VERSION}"
          cd charts/flask-app
          sed -i "s/tag: .*/tag: ${VERSION}/g" ./values.yaml
          cat ./values.yaml

      - name: Package Helm Chart
        run: |
          helm package charts/flask-app
          mv flask-app-*.tgz charts/
      
      - name: Upload Helm Chart to S3
        run: |
          aws s3 cp charts/flask-app-*.tgz s3://helm-flask-star-images/charts/
      
      - name: Generate and Upload index.yaml
        run: |
          helm repo index charts/ --url https://helm-flask-star-images.s3.amazonaws.com/charts 
          aws s3 cp charts/index.yaml s3://helm-flask-star-images/charts/index.yaml